# Generated by Django 5.2 on 2025-05-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "law_type",
                    models.CharField(
                        choices=[
                            ("bo_luat", "Bộ luật"),
                            ("luat", "Luật"),
                            ("nghi_dinh", "Nghị định"),
                            ("nghi_quyet", "Nghị quyết"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "crawl_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Thời gian crawl dữ liệu"
                    ),
                ),
                (
                    "effective_start",
                    models.DateField(help_text="Ngày bắt đầu có hiệu lực"),
                ),
                (
                    "effective_end",
                    models.DateField(
                        blank=True, help_text="Ngày hết hiệu lực, nếu có", null=True
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("chinh_tri", "Chính trị"),
                            ("dat_dai", "Đất đai"),
                            ("kinh_te", "Kinh tế"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
